# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='subtitle',
        ),
    ]
